// Judge recipes with Jev (#J4) and store the results.
//
//   npm run judge:recipes            # replays cache; writes lib/recipes/judgments.generated.ts
//   npm run judge:recipes -- --live  # new API calls
//
// Run again whenever RECIPES in lib/seedData.ts changes (#14). Also judges
// eval/jev/recipe-probes.json — recipes with an obvious best day — and checks
// that Jev's best day is an acceptable one. Probe results are reported, not
// stored in the app's judgments.

import { readFileSync, writeFileSync } from "node:fs";
import { asNoul, asScore, JEV_MODEL } from "../lib/jev/api.ts";
// Import modules directly, not lib/recipes/index.ts: the index re-exports
// the file this script generates.
import { codeTags, macroLevels } from "../lib/recipes/facts.ts";
import { RUBRIC_VERSION, fitQuestionId, recipeJudgmentRequest } from "../lib/recipes/jevRecipeQuestions.ts";
import { bestDayType, rankSwaps } from "../lib/recipes/swaps.ts";
import {
  DAY_TYPES,
  type DayType,
  type JudgmentFile,
  type RecipeFacts,
  type RecipeJudgment,
} from "../lib/recipes/types.ts";
import { RECIPES } from "../lib/seedData.ts";
import { createCachedJevClient, pool } from "./jevClient.ts";

const live = process.argv.includes("--live");
const client = createCachedJevClient(`eval/jev/cache/${JEV_MODEL}_recipes.json`, { live });

type Probe = RecipeFacts & { expectBest: DayType[] };
const probes: Probe[] = JSON.parse(readFileSync("eval/jev/recipe-probes.json", "utf8"));

async function judge(r: RecipeFacts): Promise<RecipeJudgment> {
  const res = await client.ask(recipeJudgmentRequest(r));
  const fit = {} as RecipeJudgment["fit"];
  for (const day of DAY_TYPES) {
    const a = asScore(res.answers[fitQuestionId(day)]);
    if (!a) throw new Error(`No score for ${r.id} ${day}`);
    fit[day] = { score: Math.round(a.score * 100) / 100, confidence: a.confidence };
  }
  const tag = (id: string) => {
    const a = asNoul(res.answers[id]);
    if (!a) throw new Error(`No noul for ${r.id} ${id}`);
    return a.noul;
  };
  return { fit, tags: { one_pan: tag("one_pan"), good_leftovers: tag("good_leftovers") } };
}

async function judgeAll(recipes: RecipeFacts[]): Promise<JudgmentFile> {
  const results = await pool(recipes, judge, 6);
  return {
    model: JEV_MODEL,
    rubric: RUBRIC_VERSION,
    generated: new Date().toISOString().slice(0, 10),
    recipes: Object.fromEntries(recipes.map((r, i) => [r.id, results[i]])),
  };
}

const seed = await judgeAll(RECIPES);
const probe = await judgeAll(probes);
client.save();
// Keep the old date when nothing changed, so a replay leaves the file identical
// (CI fails on a diff, which catches recipes edited without re-judging).
try {
  const { RECIPE_JUDGMENTS: previous } = await import("../lib/recipes/judgments.generated.ts");
  const same = (f: JudgmentFile) => JSON.stringify({ m: f.model, r: f.rubric, x: f.recipes });
  if (same(previous) === same(seed)) seed.generated = previous.generated;
} catch {
  // First run: no previous file.
}
writeFileSync(
  "lib/recipes/judgments.generated.ts",
  `// GENERATED by scripts/judge-recipes.ts — do not edit. Re-run after changing RECIPES.\n` +
    `import type { JudgmentFile } from "./types.ts";\n\n` +
    `export const RECIPE_JUDGMENTS: JudgmentFile = ${JSON.stringify(seed, null, 2)};\n`,
);

// --- report ---------------------------------------------------------------

const short: Record<DayType, string> = {
  hard_day: "hard", lift_day: "lift", pre_long_run: "pre-run", rest_day: "rest", recovery_day: "recov",
};
function table(title: string, recipes: RecipeFacts[], file: JudgmentFile, expected: (r: RecipeFacts) => DayType[]) {
  console.log(`\n## ${title}\n`);
  console.log(`${"recipe".padEnd(44)} ${DAY_TYPES.map((d) => short[d].padStart(7)).join("")}  best      expected           1pan  lftv  code tags`);
  let agree = 0;
  for (const r of recipes) {
    const j = file.recipes[r.id];
    const best = bestDayType(file, r.id)!;
    const ok = expected(r).includes(best);
    if (ok) agree++;
    const lv = macroLevels(r);
    console.log(
      `${r.title.slice(0, 43).padEnd(44)} ${DAY_TYPES.map((d) => j.fit[d].score.toFixed(2).padStart(7)).join("")}  ` +
        `${short[best].padEnd(8)}${ok ? "✓" : "✗"} ${expected(r).map((d) => short[d]).join("/").padEnd(18)} ` +
        `${j.tags.one_pan.toFixed(2)}  ${j.tags.good_leftovers.toFixed(2)}  ${codeTags(r).join(",")}  [P ${lv.protein}, C ${lv.carbohydrate}, F ${lv.fat}]`,
    );
  }
  console.log(`\nBest day agrees with expected: ${agree}/${recipes.length}`);
}

const seedDayTag = (r: RecipeFacts) => {
  const tags = (r as RecipeFacts & { tags?: string[] }).tags ?? [];
  return DAY_TYPES.filter((d) => tags.includes(d));
};
table("Seed recipes (expected = founder's day tag)", RECIPES, seed, seedDayTag);

// The product question: on the founder's tagged day, is this recipe the best
// dinner we have, or would rankSwaps suggest another one?
console.log(`\n## Swap check: seed recipe on its tagged day vs the other seed recipes\n`);
const ids = RECIPES.map((r) => r.id);
for (const r of RECIPES) {
  const day = seedDayTag(r)[0];
  if (!day) continue;
  const swaps = rankSwaps(seed, day, r.id, ids);
  const title = (id: string) => RECIPES.find((x) => x.id === id)?.title ?? id;
  console.log(
    `${r.title.slice(0, 43).padEnd(44)} ${short[day].padEnd(8)} ` +
      (swaps.length ? `swap → ${title(swaps[0].recipeId)} (+${swaps[0].gain.toFixed(2)})` : "keep ✓"),
  );
}
table("Probe recipes", probes, probe, (r) => (r as Probe).expectBest);
const s = client.stats;
console.log(`\ncost: ${s.calls} live + ${s.cached} cached calls, ${s.inputTokens} input tokens ≈ $${((s.inputTokens / 1e6) * 0.042).toFixed(5)}`);
console.log("wrote lib/recipes/judgments.generated.ts");
