// GENERATED by scripts/judge-recipes.ts — do not edit. Re-run after changing RECIPES.
import type { JudgmentFile } from "./types.ts";

export const RECIPE_JUDGMENTS: JudgmentFile = {
  "model": "jev-1.13.0",
  "generated": "2026-09-30",
  "recipes": {
    "sheet_pan_chicken_sweet_potato": {
      "fit": {
        "hard_day": {
          "score": 2.15,
          "confidence": 0.77
        },
        "lift_day": {
          "score": 2.73,
          "confidence": 0.73
        },
        "pre_long_run": {
          "score": 1.4,
          "confidence": 0.55
        },
        "rest_day": {
          "score": 1.69,
          "confidence": 0.69
        },
        "recovery_day": {
          "score": 2.88,
          "confidence": 0.88
        }
      },
      "tags": {
        "one_pan": 0.98,
        "good_leftovers": 0.87
      }
    },
    "monday_chicken": {
      "fit": {
        "hard_day": {
          "score": 0.86,
          "confidence": 0.84
        },
        "lift_day": {
          "score": 1.61,
          "confidence": 0.54
        },
        "pre_long_run": {
          "score": 0,
          "confidence": 1
        },
        "rest_day": {
          "score": 2.9,
          "confidence": 0.9
        },
        "recovery_day": {
          "score": 0.96,
          "confidence": 0.82
        }
      },
      "tags": {
        "one_pan": 0.94,
        "good_leftovers": 0.68
      }
    },
    "salmon_bowls": {
      "fit": {
        "hard_day": {
          "score": 2.19,
          "confidence": 0.72
        },
        "lift_day": {
          "score": 3,
          "confidence": 1
        },
        "pre_long_run": {
          "score": 1.25,
          "confidence": 0.73
        },
        "rest_day": {
          "score": 1.7,
          "confidence": 0.69
        },
        "recovery_day": {
          "score": 2.87,
          "confidence": 0.87
        }
      },
      "tags": {
        "one_pan": 0.05,
        "good_leftovers": 0.38
      }
    },
    "ground_beef_stir_fry": {
      "fit": {
        "hard_day": {
          "score": 1.08,
          "confidence": 0.85
        },
        "lift_day": {
          "score": 1.21,
          "confidence": 0.79
        },
        "pre_long_run": {
          "score": 0.03,
          "confidence": 0.97
        },
        "rest_day": {
          "score": 2.12,
          "confidence": 0.51
        },
        "recovery_day": {
          "score": 1.63,
          "confidence": 0.31
        }
      },
      "tags": {
        "one_pan": 0.88,
        "good_leftovers": 0.83
      }
    },
    "carb_forward_pasta": {
      "fit": {
        "hard_day": {
          "score": 2.92,
          "confidence": 0.92
        },
        "lift_day": {
          "score": 1.88,
          "confidence": 0.81
        },
        "pre_long_run": {
          "score": 2.25,
          "confidence": 0.63
        },
        "rest_day": {
          "score": 0.03,
          "confidence": 0.97
        },
        "recovery_day": {
          "score": 2.92,
          "confidence": 0.92
        }
      },
      "tags": {
        "one_pan": 0.11,
        "good_leftovers": 0.8
      }
    },
    "weekend_recovery_eggs": {
      "fit": {
        "hard_day": {
          "score": 1.51,
          "confidence": 0.5
        },
        "lift_day": {
          "score": 1.09,
          "confidence": 0.89
        },
        "pre_long_run": {
          "score": 0.91,
          "confidence": 0.81
        },
        "rest_day": {
          "score": 1.09,
          "confidence": 0.91
        },
        "recovery_day": {
          "score": 2.96,
          "confidence": 0.96
        }
      },
      "tags": {
        "one_pan": 0.12,
        "good_leftovers": 0.3
      }
    }
  }
};
